### ISSUE TITLE
Why duplicate my project ?

### ISSUE THREAD

**Issue by izimobil** [VVyacheslav/django-rest-framework-datatables-editor#2]
Hi, I'm the author of https://github.com/izimobil/django-rest-framework-datatables/

No offense, but it seems you've just copied my whole project including the documentation and just added some code for the editor support.

Why duplicate the project ? you could have worked on a pull request or just make drf-datatables a dependency of your project.

At the very least you could have contacted me first or started a discussion on the project github page.

I know the license grants you the right to copy the code, but IMO it's not very fair nor productive because you'll have to backport all the fixes, changes, etc. into your project (which is not even a fork).

My 2 cents.

**Comment by VVyacheslav** [comment]
Hi.
First i would like to say you a big thanks for your project [django-rest-framework-datatables](https://github.com/izimobil/django-rest-framework-datatables/)

Regarding your question about working through pull requests or making drf-datatables as dependency of my project.
I wanted to create a new quite large functionality, working almost independent from your one. I want to develop it and help users. You have wrote earlier, that you didn't have enough time for develop your project. I don't want to create a pull request and probably wait for a long time, when it will be merged or rejected. I want to decide what is good and what is bad on myself and make it fast.
As you could see i did everything for make it clear, that my project is based on yours. I wrote it wherever possible.
I do not get why do you think that it was not very fair.

I couldn't make a dependency because forks are not showed in the search.

I think i created my project the way, that is the only possible and correct one.

I am ready to join my project into your one and beacome a second author if you want. But if i asked you before starting my project it would not be correct and you would tell me no.

What do you think?

Sorry for my bad english.

**Comment by izimobil** [comment]
Hi,

Don't get me wrong, I'm not upset or anything.

I've been in the opensource world for a very very long time, and believe me, duplicating code (especially a whole project) is a really bad idea, for various reasons (there are too many to be discussed here).

I don't understand why you say a pull request was not possible, even if it would have taken time to be merged (because indeed I'm quite busy with real work), you could have:

1. forked the project
2. implemented the editor functionality (like you did, but not on a copy, on a fork !)
3. propose a PR
4. improve / fix the PR if needed
5. while waiting for the PR to be merged, you could still have used your fork
6. once the PR merged, use drf-datatables

This is generally how it works, regardless of how big code changes are, duplicating is the last option (usually for dead or abandoned projects).

I'm open to review a PR if you change your mind, and of course to credit you in the authors for the functionality...
I prefer this 1000x times over having two drf-datatables on pypi that share 80% of the same code base and that are not synched !

Don't worry about your english, I'm not english native neither.

Regards.

**Comment by izimobil** [comment]
And regarding what you said at the end:

> I am ready to join my project into your one and beacome a second author if you want. But if i asked you before starting my project it would not be correct and you would tell me no.

Of course I would not have said "no" ! If you look at [django-admin-tools](https://github.com/django-admin-tools/django-admin-tools) (which I'm the author), I created a github group, and now there are many contributors that have write access. I don't see any problem with this, as long as code quality and tests are respected.

**Comment by VVyacheslav** [comment]
Ok, let's do this!

I will prepare the PR.

I'm glad we talked. Thank you!

**Comment by izimobil** [comment]
Great, I'll be happy to review the changes, I'll also contact Alan from Datatables, to see if he could grant us a license of the Editor (only for development / testing purposes of course).

Regards.

**Comment by VVyacheslav** [comment]
I've alredy contacted with Alan.
I'll reply you by email.

**Comment by VVyacheslav** [comment]
Hi!

I've created PR. I hope everything is ok.
I will appreciate you for any refers to me as the author of the editor
functionality in readme file or wherever. Maybe it'll help me find a job.

Regards!

ср, 17 июл. 2019 г. в 16:45, David Jean Louis <notifications@github.com>:
