### ISSUE TITLE
It doesn't work on Django 3.0 by the library from django.utils import six

### ISSUE THREAD

**Issue by alejandrovelez243** [VVyacheslav/django-rest-framework-datatables-editor#6]

**Comment by mgpearce48** [comment]
I had to install six separately and change the import statement accordingly. Whilst the data is displaying I still haven't managed to get the editor buttons working ("add", "edit", "delete"). Any further advice on this?

**Comment by toastedcrumpets** [comment]
Confirming the issue here
To provide some more context for this issue, the vendor library six was removed in Django:
https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
This package needs to be patched to either depend on six, or have the compatibility removed. 

Haven't checked out the buttons issue yet.

**Comment by VVyacheslav** [comment]
Thank you for your interest! I am sorry I have delayed this update. I have published version 0.3.3 with support of Django 3.0.
